// Regenerates shared/src/secrets.data.ts from the readable source.
//
// Run with `npm run seal` after editing shared/src/secrets.source.ts, and commit both files.
// server/src/sealtest.ts fails if they ever disagree, so a forgotten seal cannot ship.
import { writeFileSync } from 'node:fs';
import { SECRET_SOURCE } from '../shared/src/secrets.source';
import { seal } from '../shared/src/secrets';

const blob = seal(SECRET_SOURCE);
const out = `// GENERATED by \`npm run seal\` from secrets.source.ts. Do not edit by hand.
//
// This is the apocrypha, sealed so the shipped bundle does not spell out which sign each unlisted
// spell wants. See secrets.ts for exactly how much that is worth.
export const SEALED = '${blob}';
`;
writeFileSync(new URL('../shared/src/secrets.data.ts', import.meta.url), out);
console.log(`sealed ${SECRET_SOURCE.length} spells into ${blob.length} characters`);
